### ISSUE TITLE
LibreTranslate on Ubuntu

### ISSUE THREAD

**Issue by srk2014** [LibreTranslate/LibreTranslate#125]
Team:
Thanks for offering this tool. I am trying to set this one on Ubuntu, and followed the instructions as outlined. However, I am seeing the following "VersionConflict" error. Any suggestion to address this issue? After following these steps, how can I map the libretranslate server to a domain of interest?

Cloning into '/home/libretranslate/LibreTranslate'...
remote: Enumerating objects: 833, done.
remote: Counting objects: 100% (169/169), done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 833 (delta 103), reused 84 (delta 73), pack-reused 664
Receiving objects: 100% (833/833), 495.42 KiB | 3.93 MiB/s, done.
Resolving deltas: 100% (462/462), done.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (virtualenv 20.0.17 (/usr/lib/python3/dist-packages), Requirement.parse('virtualenv==16.7.8'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'virtualenv==16.7.8' distribution was not found and is required by the application
/home/libretranslate/LibreTranslate-init/setup.sh: 22: /home/libretranslate/LibreTranslate/env/bin/pip: not found
/home/libretranslate/LibreTranslate-init/setup.sh: 25: /home/libretranslate/LibreTranslate/env/bin/pip: not found
/home/libretranslate/LibreTranslate-init/setup.sh: 26: /home/libretranslate/LibreTranslate/env/bin/libretranslate: not found

**Comment by pierotofy** [comment]
Is this a fresh installation of Ubuntu? Something looks broken.

**Comment by srk2014** [comment]
Ubuntu 20.0.4 was released in 2020. I believe the one on Libre is Ubuntu 16.

**Comment by srk2014** [comment]
Thanks again, PJ. I already set the dns zone for the domain of interest to the ip address, and also connected the localhost server with nginx using a new config file. However, that still has not taken the subdomain live. It appears that the nginx server is not seeing this newly created config file.

**Comment by PJ-Finlay** [comment]
You want to map the domain name to the IP of the server you will be using (localhost is just the server you're currently on). Then you can run the setup scripts on that server.  If you need Nginx to reload the config file you can restart the server or run:
```
systemctl restart nginx

```
