### ISSUE TITLE
en as frontend source language is not supported

### ISSUE THREAD

**Issue by lizongshen** [LibreTranslate/LibreTranslate#185]
[root@DESKTOP-B0B9UFO code]# docker run -ti --rm -p 5000:5000 libretranslate/libretranslate
Updating language models
ERROR:root:(RemoteDisconnected('Remote end closed connection without response'),)
Cannot update models (normal if you're offline): Local package index not found, use package.update_package_index() to load it
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:apscheduler.scheduler:Added job "remove_translated_files" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
Traceback (most recent call last):
  File "/usr/local/bin/libretranslate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/app/main.py", line 113, in main
    app = create_app(args)
  File "/usr/local/lib/python3.8/site-packages/app/app.py", line 135, in create_app
    raise AttributeError(
AttributeError: en as frontend source language is not supported.
INFO:apscheduler.scheduler:Scheduler has been shut down

**Comment by Medallyon** [comment]
I get the same `AttributeError`, with a different stacktrace:

```bash
medallyon@MEDALLYON:/mnt/d/Medallyon/Desktop/transplex$ libretranslate
Updating language models
Found 44 models
Downloading Arabic → English (1.0) ...
ERROR:root:(URLError(gaierror(-5, 'No address associated with hostname')),)
Cannot update models (normal if you're offline): expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/home/medallyon/.local/bin/libretranslate", line 8, in <module>
    sys.exit(main())
  File "/home/medallyon/.local/lib/python3.8/site-packages/app/main.py", line 107, in main
    app = create_app(args)
  File "/home/medallyon/.local/lib/python3.8/site-packages/app/app.py", line 97, in create_app
    raise AttributeError(
AttributeError: en as frontend source language is not supported.
```

This is on Ubuntu 20.04 with the Linux Subsystem on Windows 10. I can't install it on Windows 10 because some of the dependencies (pyICU, polyglot) don't want to install.

**Comment by PJ-Finlay** [comment]
In both cases the underlying issue is that the models failed to download.

Ex:
```
ERROR:root:(RemoteDisconnected('Remote end closed connection without response'),)
```

```
ERROR:root:(URLError(gaierror(-5, 'No address associated with hostname')),)
```

**Comment by TheFrenchGhosty** [comment]
It's a bug because `./install_models.py` doesn't run when the container is being created.

A workaround is to just attach to the container and execute it by hand.

(ping @pierotofy )

**Comment by dingedi** [comment]
this bug also appears when launching the app 
`python3 main.py` without any args
if the es language is not installed it displays the error, maybe it would be better to take another language installed, that would avoid having to specify the languages? @pierotofy

**Comment by pierotofy** [comment]
Agree, a different default should be chosen.

**Comment by TheFrenchGhosty** [comment]
> It's a bug because `./install_models.py` doesn't/fails to run when the container is being created.
> 
> A (bad) workaround is to just attach to the container and execute it by hand.
> 
> (ping @pierotofy )

This is still an issue.

**Comment by PJ-Finlay** [comment]
```
ERROR:root:(<HTTPError 503: 'Service Unavailable'>,)

```

@EsmailELBoBDev2 it looks like Argos Translate is failing to connect to the CDN.

**Comment by EsmailELBoBDev2** [comment]
Oh yes I know, I saw the 503 Error but i'm confused why or how to fix it

**Comment by EsmailELBoBDev2** [comment]
Now it downloads some of modules so i think it's either website blocks me (thinks im bot) or the website itself have difficult times
```bash
libretranslate    | 2022-02-27T12:59:10.726641936Z ERROR:root:(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
libretranslate    | 2022-02-27T12:59:19.670942538Z INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
libretranslate    | 2022-02-27T12:59:19.671721224Z INFO:apscheduler.scheduler:Added job "remove_translated_files" to job store "default"
libretranslate    | 2022-02-27T12:59:19.671783850Z INFO:apscheduler.scheduler:Scheduler started
libretranslate    | 2022-02-27T12:59:19.672146021Z Updating language models
libretranslate    | 2022-02-27T12:59:19.672162568Z Found 54 models
libretranslate    | 2022-02-27T12:59:19.672168898Z Downloading Arabic → English (1.0) ...
libretranslate    | 2022-02-27T12:59:19.672173859Z Downloading Azerbaijani → English (1.5) ...
libretranslate    | 2022-02-27T12:59:19.672178240Z Downloading Chinese → English (1.1) ...
libretranslate    | 2022-02-27T12:59:19.672182430Z Downloading Czech → English (1.5) ...
libretranslate    | 2022-02-27T12:59:19.672186358Z Downloading Dutch → English (1.4) ...
libretranslate    | 2022-02-27T12:59:19.672190175Z Downloading English → Arabic (1.0) ...
libretranslate    | 2022-02-27T12:59:19.672194155Z Downloading English → Azerbaijani (1.5) ...
libretranslate    | 2022-02-27T12:59:19.672199643Z Downloading English → Chinese (1.1) ...
libretranslate    | 2022-02-27T12:59:19.672203771Z Downloading English → Czech (1.5) ...
libretranslate    | 2022-02-27T12:59:19.672207752Z Downloading English → Dutch (1.4) ...
libretranslate    | 2022-02-27T12:59:19.672211619Z Downloading English → Esperanto (1.5) ...
libretranslate    | 2022-02-27T12:59:19.672215491Z Downloading English → Finnish (1.5) ...
libretranslate    | 2022-02-27T12:59:19.672219330Z Downloading English → French (1.0) ...
libretranslate    | 2022-02-27T12:59:19.672223244Z Downloading English → German (1.0) ...
libretranslate    | 2022-02-27T12:59:19.672227063Z Downloading English → Greek (1.5) ...
libretranslate    | 2022-02-27T12:59:19.672230869Z Downloading English → Hindi (1.1) ...
libretranslate    | 2022-02-27T12:59:19.672234646Z Downloading English → Hungarian (1.5) ...
libretranslate    | 2022-02-27T12:59:19.672238426Z Downloading English → Indonesian (1.2) ...
libretranslate    | 2022-02-27T12:59:19.672242244Z Downloading English → Irish (1.1) ...
libretranslate    | 2022-02-27T12:59:19.672246029Z Downloading English → Italian (1.0) ...
libretranslate    | 2022-02-27T12:59:19.672249813Z Downloading English → Japanese (1.1) ...
libretranslate    | 2022-02-27T12:59:19.672253602Z Downloading English → Korean (1.1) ...
libretranslate    | 2022-02-27T12:59:19.672257514Z Downloading English → Persian (1.5) ...
libretranslate    | 2022-02-27T12:59:19.672261327Z Downloading English → Polish (1.1) ...
libretranslate    | 2022-02-27T12:59:19.672265140Z Downloading English → Portuguese (1.0) ...
libretranslate    | 2022-02-27T12:59:19.672268945Z Downloading English → Russian (1.1) ...
libretranslate    | 2022-02-27T12:59:19.672272762Z Downloading English → Slovak (1.5) ...
libretranslate    | 2022-02-27T12:59:19.672276547Z Downloading English → Spanish (1.0) ...
libretranslate    | 2022-02-27T12:59:19.672280328Z Downloading English → Swedish (1.5) ...
libretranslate    | 2022-02-27T12:59:19.672284102Z Downloading English → Turkish (1.5) ...
libretranslate    | 2022-02-27T12:59:19.672299587Z Downloading English → Ukranian (1.4) ...
libretranslate    | 2022-02-27T12:59:19.672304395Z Downloading English → Vietnamese (1.2) ...
libretranslate    | 2022-02-27T12:59:19.672308331Z Downloading Esperanto → English (1.5) ...
libretranslate    | 2022-02-27T12:59:19.672312272Z Downloading Finnish → English (1.5) ...
libretranslate    | 2022-02-27T12:59:19.672316106Z Downloading French → English (1.0) ...
libretranslate    | 2022-02-27T12:59:19.672319942Z Downloading German → English (1.0) ...
libretranslate    | 2022-02-27T12:59:19.672323784Z Downloading Greek → English (1.5) ...
libretranslate    | 2022-02-27T12:59:19.672327638Z Downloading Hindi → English (1.1) ...
libretranslate    | 2022-02-27T12:59:19.672331490Z Downloading Hungarian → English (1.5) ...
libretranslate    | 2022-02-27T12:59:19.672335331Z Downloading Indonesian → English (1.2) ...
libretranslate    | 2022-02-27T12:59:19.672339259Z Downloading Irish → English (1.1) ...
libretranslate    | 2022-02-27T12:59:19.672343108Z Downloading Italian → English (1.0) ...
libretranslate    | 2022-02-27T12:59:19.672346900Z Downloading Japanese → English (1.1) ...
libretranslate    | 2022-02-27T12:59:19.672350772Z Downloading Korean → English (1.1) ...
libretranslate    | 2022-02-27T12:59:19.672354565Z Downloading Persian → English (1.5) ...
libretranslate    | 2022-02-27T12:59:19.672358436Z Cannot update models (normal if you're offline): expected str, bytes or os.PathLike object, not NoneType
libretranslate    | 2022-02-27T12:59:19.672435958Z Traceback (most recent call last):
libretranslate    | 2022-02-27T12:59:19.672452239Z   File "/usr/local/bin/libretranslate", line 8, in <module>
libretranslate    | 2022-02-27T12:59:19.672462802Z     sys.exit(main())
libretranslate    | 2022-02-27T12:59:19.672470939Z   File "/usr/local/lib/python3.8/site-packages/app/main.py", line 116, in main
libretranslate    | 2022-02-27T12:59:19.672479867Z     app = create_app(args)
libretranslate    | 2022-02-27T12:59:19.672487133Z   File "/usr/local/lib/python3.8/site-packages/app/app.py", line 138, in create_app
libretranslate    | 2022-02-27T12:59:19.672494758Z     frontend_argos_language_source = languages[0]
libretranslate    | 2022-02-27T12:59:19.672501978Z IndexError: list index out of range
libretranslate    | 2022-02-27T12:59:19.672511415Z INFO:apscheduler.scheduler:Scheduler has been shut down
```

**Comment by PJ-Finlay** [comment]
It looks like some of the models are being downloaded successfully but others are failing. I'm not sure about the underlying cause but the models are hosted on a Digital Ocean CDN.

**Comment by EsmailELBoBDev2** [comment]
Yeah I tried to run it inside docker this time and it downloaded so indeed i think it was problem with site not lt or argos in general

**Comment by TheFrenchGhosty** [comment]
I ended up making my own image with the models included, and everything works perfectly now. 

No more issue with models not installing correctly, with a model missing, with half hour long downtime when updating...

https://github.com/TheFrenchGhosty/docker-libretranslate-quay

**Comment by EsmailELBoBDev2** [comment]
Oh yeas download worked fine with me last time so I think it was the website

Now everything works

**Comment by TheFrenchGhosty** [comment]
@EsmailELBoBDev2 I still had a missing model on my instance.

**Comment by EsmailELBoBDev2** [comment]
For me it was problem with Argos website itself (as you see above in my logs) so did you make sure your error message is not same like mine?

I did not try it but I think you could try offline mode (it should in theory fix this problem but again did not try it myself)
