### ISSUE TITLE
Latest Docker image crashing (ImportError: cannot import name 'escape' from 'jinja2')

### ISSUE THREAD

**Issue by calvinbui** [LibreTranslate/LibreTranslate#230]
```
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.8/site-packages/jinja2/__init__.py)
Traceback (most recent call last):
  File "/usr/local/bin/libretranslate", line 5, in <module>
    from app.main import main
  File "/usr/local/lib/python3.8/site-packages/app/__init__.py", line 12, in <module>
    from .main import main
  File "/usr/local/lib/python3.8/site-packages/app/main.py", line 5, in <module>
    from app.app import create_app
  File "/usr/local/lib/python3.8/site-packages/app/app.py", line 10, in <module>
    from flask import (Flask, abort, jsonify, render_template, request, send_file,
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
```

**Comment by dingedi** [comment]
Same for me

**Comment by calvinbui** [comment]
related: https://github.com/pallets/flask/issues/4494

**Comment by dingedi** [comment]
i also have this issue by installing libretranslate with pip, so its not only a docker specific bug
