### ISSUE TITLE
Unable to installing LibreTranslate locally on Windows 11

### ISSUE THREAD

**Issue by Qws** [LibreTranslate/LibreTranslate#251]
It's keeps failing at downloading the languages

Text log:
```
PS C:\Users\qws> docker run -ti --rm -p 5000:5000 libretranslate/libretranslate
Unable to find image 'libretranslate/libretranslate:latest' locally
latest: Pulling from libretranslate/libretranslate
f7a1c6dad281: Pull complete
92c59ec44e08: Pull complete
08935196cb79: Pull complete
7aa958b41dfb: Pull complete
86c7a279e304: Pull complete
36f12b3505c5: Pull complete
167e8bff4196: Pull complete
dd4ccb0ea84f: Pull complete
686756d51bc1: Pull complete
4f4fb700ef54: Pull complete
08bba9988d2e: Pull complete
Digest: sha256:f773ad69a91e798bd4c797d7e219323e67fe4b84eba7b2ab047f45a4d3a9ee2a
Status: Downloaded newer image for libretranslate/libretranslate:latest
Updating language models
Found 54 models
Downloading Arabic → English (1.0) ...
Cannot update models (normal if you're offline): IncompleteRead(81750720 bytes read, 118950 more expected)
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:apscheduler.scheduler:Added job "remove_translated_files" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
Traceback (most recent call last):
  File "/usr/local/bin/libretranslate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/app/main.py", line 121, in main
    app = create_app(args)
  File "/usr/local/lib/python3.8/site-packages/app/app.py", line 139, in create_app
    frontend_argos_language_source = languages[0]
IndexError: list index out of range
INFO:apscheduler.scheduler:Scheduler has been shut down
PS C:\Users\qws> docker run -ti --rm -p 5000:5000 libretranslate/libretranslate
Updating language models
Found 54 models
Downloading Arabic → English (1.0) ...
Downloading Azerbaijani → English (1.5) ...
sudo apt-get install -y libicu-dev python3-icu pkg-configDownloading Chinese → English (1.1) ...
Cannot update models (normal if you're offline): IncompleteRead(112165440 bytes read, 212855 more expected)
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:apscheduler.scheduler:Added job "remove_translated_files" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
INFO:waitress:Serving on http://0.0.0.0:5000
^[[A^[[A^CINFO:apscheduler.scheduler:Scheduler has been shut down
PS C:\Users\qws> docker run -ti --rm -p 5000:5000 libretranslate/libretranslate
Updating language models
Found 54 models
Downloading Arabic → English (1.0) ...
Downloading Azerbaijani → English (1.5) ...
Cannot update models (normal if you're offline): IncompleteRead(120813120 bytes read, 13650 more expected)
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:apscheduler.scheduler:Added job "remove_translated_files" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
INFO:waitress:Serving on http://0.0.0.0:5000
WARNING:waitress.queue:Task queue depth is 1
^CINFO:apscheduler.scheduler:Scheduler has been shut down
^C^C
PS C:\Users\qws> docker run -ti --rm -p 5000:5000 libretranslate/libretranslate
Updating language models
Found 54 models
Downloading Arabic → English (1.0) ...
Downloading Azerbaijani → English (1.5) ...
Downloading Chinese → English (1.1) ...
Downloading Czech → English (1.5) ...
Downloading Dutch → English (1.4) ...
Downloading English → Arabic (1.0) ...
Downloading English → Azerbaijani (1.5) ...
Downloading English → Chinese (1.1) ...
Downloading English → Czech (1.5) ...
Downloading English → Dutch (1.4) ...
Downloading English → Esperanto (1.5) ...
Downloading English → Finnish (1.5) ...
Downloading English → French (1.0) ...
Downloading English → German (1.0) ...
Downloading English → Greek (1.5) ...
Downloading English → Hindi (1.1) ...
Downloading English → Hungarian (1.5) ...
Cannot update models (normal if you're offline): IncompleteRead(109776008 bytes read, 201654 more expected)
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:apscheduler.scheduler:Added job "remove_translated_files" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
INFO:waitress:Serving on http://0.0.0.0:5000
^[[A^[[B^CINFO:apscheduler.scheduler:Scheduler has been shut down
PS C:\Users\qws> docker run -ti --rm -p 5000:5000 libretranslate/libretranslate
Updating language models
Found 54 models
Downloading Arabic → English (1.0) ...
Downloading Azerbaijani → English (1.5) ...
Downloading Chinese → English (1.1) ...
Cannot update models (normal if you're offline): IncompleteRead(112306560 bytes read, 71735 more expected)
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:apscheduler.scheduler:Added job "remove_translated_files" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
INFO:waitress:Serving on http://0.0.0.0:5000
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 1
^CINFO:apscheduler.scheduler:Scheduler has been shut down
```

What can I do at this point? Just keep trying and hope it works one day?

**Comment by PJ-Finlay** [comment]
Failing to download seems like a common issue we're having. I'm looking at adding retry logic to Argos Translate but we can also consider adding this type of functionality to LibreTranslate.

I use the standard library to download packages in Argos Translate to reduce dependencies but LibreTranslate already includes `requests` and we may have better results using it. The Argos Translate packaging code should be modular enough that you can get package paths from the index, download them manually, and then install them with Argos Translate.
