### ISSUE TITLE
Issue with module "jinja2" and module "Flask"

### ISSUE THREAD

**Issue by Tecubo** [LibreTranslate/LibreTranslate#265]
Hello,
I installed libretranslate using the simple command : `pip install libretranslate`
The installation worked well but when I try to launch it with command : `libretranslate`, I had this error :

```
libretranslate
Traceback (most recent call last):
  File "/home/teo/.local/bin/libretranslate", line 5, in <module>
    from app.main import main
  File "/home/teo/.local/lib/python3.10/site-packages/app/__init__.py", line 12, in <module>
    from .main import main
  File "/home/teo/.local/lib/python3.10/site-packages/app/main.py", line 5, in <module>
    from app.app import create_app
  File "/home/teo/.local/lib/python3.10/site-packages/app/app.py", line 10, in <module>
    from flask import (Flask, abort, jsonify, render_template, request, send_file,
  File "/home/teo/.local/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/home/teo/.local/lib/python3.10/site-packages/jinja2/__init__.py)

```

This is an issue with the module escape which is not supported anymore in newer versions of Jinja, which is used bu Flask V1.
See : [https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2](url)

To solve the problem, I updated Flask as the stackoverflow answer proposes but this is not a satisfaying solution. This library should update its dependancies.

Thank you

**Comment by nobicycle** [comment]
Hi Tecubo
How did you fix exactly?
I tried the below but flask did not update to  2.1 and I cannot find the requirements file. Perhaps it is because torch was installed by a whl file and no update is possible???
```
**`(libretranslate)** [user@tower libretranslate]$ **pip install flask update**
Requirement already satisfied: flask in ./lib/python3.10/site-packages (1.1.2)
Collecting update
  Downloading update-0.0.1-py2.py3-none-any.whl (2.9 kB)
Requirement already satisfied: itsdangerous>=0.24 in ./lib/python3.10/site-packages (from flask) (2.0.1)
Requirement already satisfied: Jinja2>=2.10.1 in ./lib/python3.10/site-packages (from flask) (3.1.2)
Requirement already satisfied: Werkzeug>=0.15 in ./lib/python3.10/site-packages (from flask) (2.1.2)
Requirement already satisfied: click>=5.1 in ./lib/python3.10/site-packages (from flask) (8.1.3)
Collecting style==1.1.0
  Downloading style-1.1.0-py2.py3-none-any.whl (6.4 kB)
Requirement already satisfied: MarkupSafe>=2.0 in ./lib/python3.10/site-packages (from Jinja2>=2.10.1->flask) (2.1.1)
Installing collected packages: style, update
Successfully installed style-1.1.0 update-0.0.1

````

**Comment by dingedi** [comment]
the dependencies have been updated libretranslate has been using flask 2.x for a few months but the version of libretranslate on pypi which is available in `pip install libretranslate` is not up to date.
you can install libretranslate from source by making a clone of the github repository in the meantime

ping @pierotofy

**Comment by pierotofy** [comment]
Retry with the new release, if the problem persists feel free to reopen? :pray:
