### ISSUE TITLE
Certificate Verify Failed

### ISSUE THREAD

**Issue by archer31** [LibreTranslate/LibreTranslate#278]
I'm having some issues with getting the languages to download.

```
#10 128.0 (URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')),)
#10 128.0 Updating language models
#10 128.0 Found 58 models
#10 128.0 Downloading Arabic → English (1.0) ...
#10 128.0 Traceback (most recent call last):
#10 128.0   File "./install_models.py", line 12, in <module>
#10 128.0     check_and_install_models(force=True, load_only_lang_codes=lang_codes)
#10 128.0   File "/app/app/init.py", line 54, in check_and_install_models
#10 128.0     download_path = available_package.download()
#10 128.0   File "/usr/local/lib/python3.8/site-packages/argostranslate/package.py", line 217, in download
#10 128.0     raise Exception(f"Download failed for {url}")
#10 128.0 NameError: name 'url' is not defined
```
This occurs either during the build process or when using the pre-built image on DockerHub.

I know that I am behind a firewall that is doing ssl inspections. I already tried to remedy this by including my own cert by including `RUN /bin/cat /my_cert.pem >>$(python -m certifi)` (after copying my cert into the container of course) in the dockerfile build process but this still does not resolve the issue.

It might be best to include an option for either disabling ssl and/or allowing users to better specify certificates to include in the CA (though I'm not familiar enough with the project to know why my fix does not work).

**Comment by pierotofy** [comment]
Ah, SSL... the gift that keeps on giving. :smile: 

Yeah the firewall might be tampering with the certificate. Perhaps a feature could be added in argos to set an environment variable that disables SSL verification, then add an argument to LibreTranslate's dockerfile to set the variable conditionally.

**Comment by hendursaga** [comment]
Or, hear me out, do certificate pinning - multiply your troubles! :laughing:
