### ISSUE TITLE
Docker installation fails with "No usable temporary directory found" and "no space left on device", but 450GB+ available

### ISSUE THREAD

**Issue by 0x199x** [LibreTranslate/LibreTranslate#297]
During installation of LibreTranslate docker container, it fails midway through with the error "no space left on device"

The disk it is being installed to has more than 450GB free space, and 32GB RAM is available on the system.   There should be ample resources available.

If not disk, and if not RAM, what limit is it hitting?  The error also mentions "No usable temporary directory found", perhaps due to disk space error

OS is EndeavourOS linux

![image](https://user-images.githubusercontent.com/89231731/184503453-4a534d79-30f9-4d2f-9c3a-3091532e2a36.png)

![image](https://user-images.githubusercontent.com/89231731/184503570-5d28e7d4-5cde-4aa8-81cd-9b63c33a82ce.png)

```
$ docker run -ti --rm -p 5000:5000 libretranslate/libretranslate
...
...
...
Downloading English → Turkish (1.5) ...
Downloading English → Ukranian (1.4) ...
Downloading Esperanto → English (1.5) ...
Downloading Finnish → English (1.5) ...
Cannot update models (normal if you're offline): [Errno 28] No space left on device
Traceback (most recent call last):
  File "/usr/local/bin/libretranslate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/app/main.py", line 146, in main
    app = create_app(args)
  File "/usr/local/lib/python3.8/site-packages/app/app.py", line 113, in create_app
    remove_translated_files.setup(get_upload_dir())
  File "/usr/local/lib/python3.8/site-packages/app/app.py", line 33, in get_upload_dir
    upload_dir = os.path.join(tempfile.gettempdir(), "libretranslate-files-translate")
  File "/usr/local/lib/python3.8/tempfile.py", line 286, in gettempdir
    tempdir = _get_default_tempdir()
  File "/usr/local/lib/python3.8/tempfile.py", line 218, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/app']
```

**Comment by AbdelhamidLarachi** [comment]
same here on OSX 11.6.7 have you found the issue ? please share if you did. ty

**Comment by pierotofy** [comment]
Try increasing the disk image size from the docker settings: https://docs.docker.com/desktop/settings/mac/
