### ISSUE TITLE
Error while downloading language models

### ISSUE THREAD

**Issue by vaggos-thanos** [LibreTranslate/LibreTranslate#369]
When I run the `./install_models.py` script it downloads some models but crashes after.
Also I am using a raspberry pi (RPI OS)
```
Updating language models
Found 58 models
Downloading Arabic → English (1.0) ...
Downloading Azerbaijani → English (1.5) ...
Downloading Catalan → English (1.7) ...
Downloading Chinese → English (1.7) ...
Downloading Czech → English (1.5) ...
Downloading Danish → English (1.3) ...
Downloading Dutch → English (1.4) ...
Downloading English → Arabic (1.0) ...
Downloading English → Azerbaijani (1.5) ...
Downloading English → Catalan (1.7) ...
Downloading English → Chinese (1.7) ...
Downloading English → Czech (1.5) ...
Downloading English → Danish (1.3) ...
Downloading English → Dutch (1.4) ...
Downloading English → Esperanto (1.5) ...
Downloading English → Finnish (1.5) ...
Downloading English → French (1.0) ...
Downloading English → German (1.0) ...
Downloading English → Greek (1.5) ...
Downloading English → Hebrew (1.5) ...
Downloading English → Hindi (1.1) ...
Downloading English → Hungarian (1.5) ...
Downloading English → Indonesian (1.2) ...
Downloading English → Irish (1.1) ...
Downloading English → Italian (1.0) ...
Downloading English → Japanese (1.1) ...
Traceback (most recent call last):
  File "/home/vaggos/vaggos_hdd/LibreTranslate/./install_models.py", line 12, in <module>
    check_and_install_models(force=True, load_only_lang_codes=lang_codes)
  File "/home/vaggos/vaggos_hdd/LibreTranslate/app/init.py", line 53, in check_and_install_models
    package.install_from_path(download_path)
  File "/home/vaggos/.local/lib/python3.9/site-packages/argostranslate/package.py", line 183, in install_from_path
    raise Exception("Not a valid Argos Model (must be a zip archive)")
Exception: Not a valid Argos Model (must be a zip archive)
```

**Comment by pierotofy** [comment]
If there was a corrupt model this should be fixed with the latest version as we haven't received other reports since. 🙏 We can re-open if the issue persists.
