### ISSUE TITLE
cant update models, no url is defined

### ISSUE THREAD

**Issue by SaruRonin** [LibreTranslate/LibreTranslate#397]
i have an old container from 2 months ago that i ran which still runs libretranslate perfectly. 
however when i wanted to start a new container to run on azure it wouldnt work anymore and i got the following error when using docker (multiple tries):

2023-01-24 10:49:36 (<HTTPError 403: 'Forbidden'>,)
2023-01-24 10:49:37 (<HTTPError 403: 'Forbidden'>,)
2023-01-24 10:49:37 (<HTTPError 403: 'Forbidden'>,)
2023-01-24 10:49:37 (<HTTPError 403: 'Forbidden'>,)
2023-01-24 10:49:37 Traceback (most recent call last):
2023-01-24 10:49:37   File "./venv/bin/libretranslate", line 33, in <module>
2023-01-24 10:49:37     sys.exit(load_entry_point('libretranslate==1.3.1', 'console_scripts', 'libretranslate')())
2023-01-24 10:49:37   File "/app/venv/lib/python3.8/site-packages/app/main.py", line 153, in main
2023-01-24 10:49:37     app = create_app(args)
2023-01-24 10:49:37   File "/app/venv/lib/python3.8/site-packages/app/app.py", line 139, in create_app
2023-01-24 10:49:37     frontend_argos_language_source = languages[0]
2023-01-24 10:49:37 IndexError: list index out of range
2023-01-24 10:53:17 (<HTTPError 403: 'Forbidden'>,)
2023-01-24 10:53:17 (<HTTPError 403: 'Forbidden'>,)
2023-01-24 10:53:17 (<HTTPError 403: 'Forbidden'>,)
2023-01-24 10:53:17 (<HTTPError 403: 'Forbidden'>,)
2023-01-24 10:53:17 Traceback (most recent call last):
2023-01-24 10:53:17   File "./venv/bin/libretranslate", line 33, in <module>
2023-01-24 10:53:17     sys.exit(load_entry_point('libretranslate==1.3.1', 'console_scripts', 'libretranslate')())
2023-01-24 10:53:17   File "/app/venv/lib/python3.8/site-packages/app/main.py", line 153, in main
2023-01-24 10:53:17     app = create_app(args)
2023-01-24 10:53:17   File "/app/venv/lib/python3.8/site-packages/app/app.py", line 139, in create_app
2023-01-24 10:53:17     frontend_argos_language_source = languages[0]
2023-01-24 10:53:17 IndexError: list index out of range
2023-01-24 11:18:28 (<HTTPError 403: 'Forbidden'>,)
2023-01-24 11:18:28 (<HTTPError 403: 'Forbidden'>,)
2023-01-24 11:18:28 (<HTTPError 403: 'Forbidden'>,)
2023-01-24 11:18:28 (<HTTPError 403: 'Forbidden'>,)
2023-01-24 11:18:28 Traceback (most recent call last):
2023-01-24 11:18:28   File "./venv/bin/libretranslate", line 33, in <module>
2023-01-24 11:18:28     sys.exit(load_entry_point('libretranslate==1.3.1', 'console_scripts', 'libretranslate')())
2023-01-24 11:18:28   File "/app/venv/lib/python3.8/site-packages/app/main.py", line 153, in main
2023-01-24 11:18:28     app = create_app(args)
2023-01-24 11:18:28   File "/app/venv/lib/python3.8/site-packages/app/app.py", line 139, in create_app
2023-01-24 11:18:28     frontend_argos_language_source = languages[0]
2023-01-24 11:18:28 IndexError: list index out of range
2023-01-24 10:49:37 Updating language models
2023-01-24 10:49:37 Found 58 models
2023-01-24 10:49:37 Downloading Arabic → English (1.0) ...
2023-01-24 10:49:37 Cannot update models (normal if you're offline): name 'url' is not defined
2023-01-24 10:53:17 Updating language models
2023-01-24 10:53:17 Found 58 models
2023-01-24 10:53:17 Downloading Arabic → English (1.0) ...
2023-01-24 10:53:17 Cannot update models (normal if you're offline): name 'url' is not defined
2023-01-24 11:18:28 Updating language models
2023-01-24 11:18:28 Found 58 models
2023-01-24 11:18:28 Downloading Arabic → English (1.0) ...
2023-01-24 11:18:28 Cannot update models (normal if you're offline): name 'url' is not defined

**Comment by wagesj45** [comment]
Having the same issue here.

**Comment by SaruRonin** [comment]
So far i have tried going back to previous versions but none of them seem to work for me anymore and i cant figure out why this happens.

**Comment by wagesj45** [comment]
@SaruRonin since I posted they released a new docker image. When I tried it, it worked as expected. Maybe try pulling `:latest` again.

**Comment by PJ-Finlay** [comment]
It looks like it's failing to download the models with the error `<HTTPError 403: 'Forbidden'>`. 

You can see the URLs it's trying to connect to with `export ARGOS_DEBUG=1`

Some possible issues:
- You have an old version of the Argos Translate package index with broken links. This can be fixed with `argospm update`.
- Cloudflare is blocking you're request for some reason. Older versions of Argos Translate didn't set the User -Agent header which might make this more likely.

**Comment by pierotofy** [comment]
I assume this has been fixed? If not, we can re-open 🙏 

This could also be due to a misconfigured firewall or some other network restriction.
