### ISSUE TITLE
No such file or directory: 'VERSION'

### ISSUE THREAD

**Issue by kolserdav** [LibreTranslate/LibreTranslate#433]
Can't install with pip:
```sh
pip install --global-option='I/usr/local/share/applications/Python-3.9.16/Include' -r requirements.txt
```
file `requirements.txt`:
```txt
libretranslate==1.3.10
```
thrown error:
```sh
Collecting libretranslate==1.3.10
  Using cached libretranslate-1.3.10.tar.gz (57 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-o5xl4_p5/libretranslate_ec4e6e7c67a94d80ae22014130ce7eb7/setup.py", line 6, in <module>
          version=open('VERSION').read().strip(),
      FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

```
python --version:
```sh
Python 3.9.16

```
pip --version:
```sh
pip 22.0.4 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
```

**Comment by pierotofy** [comment]
Did you `git clone` the repository first and issue the command from the `LibreTranslate` directory?

**Comment by kolserdav** [comment]
No I just install libretranslate as a library. On the local computer it worked but on the remote server this problem happens.

**Comment by pierotofy** [comment]
This *should* be fixed with the latest version. `pip install -U libretranslate`. If not, feel free to re-open? 🙏
