### ISSUE TITLE
Error while download language models

### ISSUE THREAD

**Issue by NiKh648** [LibreTranslate/LibreTranslate#449]
Hi there,

I have been trying to run Libretranslate in docker using the official image from docker hub.
https://registry.hub.docker.com/r/libretranslate/libretranslate

I am getting the below error while trying to start the container.

```
2023-06-19 16:57:25 Traceback (most recent call last):
2023-06-19 16:57:25 Updating language models
2023-06-19 16:57:25 Found 60 models
2023-06-19 16:57:25 Downloading Arabic → English (1.0) ...
2023-06-19 16:57:25 Cannot update models (normal if you're offline): Download failed for Arabic → English
2023-06-19 16:57:25   File "/app/./venv/bin/libretranslate", line 8, in <module>
2023-06-19 16:57:25     sys.exit(main())
2023-06-19 16:57:25   File "/app/venv/lib/python3.10/site-packages/libretranslate/main.py", line 189, in main
2023-06-19 16:57:25     app = create_app(args)
2023-06-19 16:57:25   File "/app/venv/lib/python3.10/site-packages/libretranslate/app.py", line 156, in create_app
2023-06-19 16:57:25     language_target_fallback = languages[0]
2023-06-19 16:57:25 IndexError: list index out of range
```

**Comment by NiKh648** [comment]
With further investigation, I found that the urls from which the model are being downloaded is not accessible. Getting below error while trying to download the models:

```
Get https://pub-dbae765fb25a4114aac1c88b90e94178.r2.dev/v1/translate-ar_en-1_0.argosmodel 1
2023-06-20 23:14:38 Get https://pub-dbae765fb25a4114aac1c88b90e94178.r2.dev/v1/translate-ar_en-1_0.argosmodel
2023-06-20 23:14:38 <urlopen error [Errno -2] Name or service not known>
2023-06-20 23:14:38 Cannot update models (normal if you're offline): name 'traceback' is not defined
2023-06-20 23:14:38 [PosixPath('/home/libretranslate/.local/share/argos-translate/packages')]
2023-06-20 23:14:38 []
2023-06-20 23:14:38 []
2023-06-20 23:15:27 (URLError(gaierror(-2, 'Name or service not known')),)
2023-06-20 23:15:27 Traceback (most recent call last):
2023-06-20 23:15:27   File "/usr/local/lib/python3.10/urllib/request.py", line 1348, in do_open
2023-06-20 23:15:27     h.request(req.get_method(), req.selector, req.data, headers,
2023-06-20 23:15:27   File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
2023-06-20 23:15:27     self._send_request(method, url, body, headers, encode_chunked)
2023-06-20 23:15:27   File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
2023-06-20 23:15:27     self.endheaders(body, encode_chunked=encode_chunked)
2023-06-20 23:15:27   File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
2023-06-20 23:15:27     self._send_output(message_body, encode_chunked=encode_chunked)
2023-06-20 23:15:27   File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
2023-06-20 23:15:27     self.send(msg)
2023-06-20 23:15:27   File "/usr/local/lib/python3.10/http/client.py", line 975, in send
2023-06-20 23:15:27     self.connect()
2023-06-20 23:15:27   File "/usr/local/lib/python3.10/http/client.py", line 1447, in connect
2023-06-20 23:15:27     super().connect()
2023-06-20 23:15:27   File "/usr/local/lib/python3.10/http/client.py", line 941, in connect
2023-06-20 23:15:27     self.sock = self._create_connection(
2023-06-20 23:15:27   File "/usr/local/lib/python3.10/socket.py", line 824, in create_connection
2023-06-20 23:15:27     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
2023-06-20 23:15:27   File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
2023-06-20 23:15:27     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2023-06-20 23:15:27 socket.gaierror: [Errno -2] Name or service not known
```

Getting below message when trying to access the url from browser:
![image](https://github.com/LibreTranslate/LibreTranslate/assets/81732625/e7c665f9-74ee-4a20-81c1-f44669e35332)

All the urls from this link provided in ArgosTranslate documentation has the same issue:
[https://www.argosopentech.com/argospm/index/](url)

**Comment by PJ-Finlay** [comment]
Do you have some sort of firewall or VPN that is preventing you from connecting to Cloudflare?

This URL is for Cloudflare R2 and works for me:
https://pub-dbae765fb25a4114aac1c88b90e94178.r2.dev/v1/translate-ar_en-1_0.argosmodel

This URL should also work if you can't access Cloudflare:
https://cdn.argosopentech.io/translate-ar_en-1_0.argosmodel
