### ISSUE TITLE
after : libretranslate --update-models  =>> TypeError: __init__() got an unexpected keyword argument 'locale_selector'  ( line 1090, in create_app)

### ISSUE THREAD

**Issue by ecxod** [LibreTranslate/LibreTranslate#470]
After updating the modules 
```
libretranslate --update-models
```
I got this : 

```
Downloading Ukranian ? English (1.4) ...
Loaded support for 32 languages (60 models total)!
Traceback (most recent call last):
File "/home/me/LibreTranslate/bin/libretranslate", line 11, in <module>
    load_entry_point('libretranslate', 'console_scripts', 'libretranslate')()
  File "/home/me/LibreTranslate/LibreTranslate/libretranslate/main.py", line 189, in main
    app = create_app(args)
  File "/home/me/LibreTranslate/LibreTranslate/libretranslate/app.py", line 1090, in create_app
    babel = Babel(app, locale_selector=get_locale)
TypeError: __init__() got an unexpected keyword argument 'locale_selector'
```

```
1073     swag = swagger(app)
1074     swag["info"]["version"] = get_version()
1075     swag["info"]["title"] = "LibreTranslate"
1076
1077     @app.route(API_URL)
1078     @limiter.exempt
1079     def spec():
1080         return jsonify(lazy_swag(swag))
1081
1082     app.config["BABEL_TRANSLATION_DIRECTORIES"] = 'locales'
1083
1084     def get_locale():
1085         override_lang = request.headers.get('X-Override-Accept-Language')
1086         if override_lang and override_lang in get_available_locale_codes():
1087             return override_lang
1088         return session.get('preferred_lang', request.accept_languages.best_match(get_available_locale_codes()))
1089
1090     babel = Babel(app, locale_selector=get_locale)
1091
1092     app.jinja_env.globals.update(_e=gettext_escaped, _h=gettext_html)
1093
1094     # Call factory function to create our blueprint
1095     swaggerui_blueprint = get_swaggerui_blueprint(SWAGGER_URL, API_URL)
1096     if args.url_prefix:
1097         app.register_blueprint(swaggerui_blueprint, url_prefix=SWAGGER_URL)
1098     else:
1099         app.register_blueprint(swaggerui_blueprint)
1100
1101     return app
```
The error you're seeing comes from this line of code:

```python
babel = Babel(app, locale_selector=get_locale)
```

The script is trying to initialize a new instance of the `Babel` class with the parameters `app` and a keyword argument `locale_selector` which is assigned the function `get_locale`. 

The error message `TypeError: __init__() got an unexpected keyword argument 'locale_selector'` tells us that the `Babel` class's constructor (the `__init__` method) does not expect a keyword argument named `locale_selector`. This means that `locale_selector` is not a valid parameter for the `Babel` class's constructor according to the version of Babel that you're using.

This issue might be caused by a couple of reasons:

**First Posibility : The version of the Babel** 

  Name: Babel
  Version: 2.11.0
  Summary: Internationalization utilities
  Home-page: https://babel.pocoo.org/
  Author: Armin Ronacher
  Author-email: armin.ronacher@active-4.com
  License: BSD
  Location: /home/me/LibreTranslate/lib/python3.9/site-packages
  Requires: pytz
  Required-by: Flask-Babel

Not the latest so I installed the latest blood from the butcher

```
Requirement already satisfied: babel in /home/me/LibreTranslate/lib/python3.9/site-packages (2.11.0)
Collecting babel
  Downloading Babel-2.12.1-py3-none-any.whl (10.1 MB)
     |¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 10.1 MB 7.4 MB/s
Installing collected packages: babel
  Attempting uninstall: babel
    Found existing installation: Babel 2.11.0
    Uninstalling Babel-2.11.0:
      Successfully uninstalled Babel-2.11.0
Successfully installed babel-2.12.1
```

Result was the same, so I updated the locale 
```
apt show locales => 2.36-8  (latest update was installed from bookworm)
# so we regenerate again
locale-gen 
```
then updated models again
``` 
(LibreTranslate) me@nirvana:~$ libretranslate --update-models

# and again the same problem : 
[...]
Downloading Ukranian ? English (1.4) ...
Loaded support for 32 languages (60 models total)!
Traceback (most recent call last):
  File "/home/translate/LibreTranslate/bin/libretranslate", line 11, in <module>
    load_entry_point('libretranslate', 'console_scripts', 'libretranslate')()
  File "/home/translate/LibreTranslate/LibreTranslate/libretranslate/main.py", line 189, in main
    app = create_app(args)
  File "/home/translate/LibreTranslate/LibreTranslate/libretranslate/app.py", line 1090, in create_app
    babel = Babel(app, locale_selector=get_locale)
TypeError: __init__() got an unexpected keyword argument 'locale_selector'
```

So it looks like it is a bug .....
(I don't know if it is related, but it seems there is no UA locale)

**Comment by ecxod** [comment]
It is also worth to notice that libretranslate 1.3.11 requires redis==4.3.4, but the latest is redis 4.6.0 which is incompatible. 
this can cause trouble when somebody does this :
```
pip install -e .
```

**Comment by pierotofy** [comment]
Does this still happen with the latest version?
