### ISSUE TITLE
exclude db from .gitignore

### ISSUE THREAD

**Issue by superset1** [LibreTranslate/LibreTranslate#477]
Hello

Please, exclude db from .gitignore because it doesnt work with ci. Image can't start

```
Traceback (most recent call last):
  File "/app/./venv/bin/libretranslate", line 8, in <module>
Loaded support for 3 languages (4 models total)!
    sys.exit(main())
  File "/app/venv/lib/python3.10/site-packages/libretranslate/main.py", line 189, in main
    app = create_app(args)
  File "/app/venv/lib/python3.10/site-packages/libretranslate/app.py", line 220, in create_app
    os.mkdir(default_mp_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/app/db/prometheus'
```

**Comment by pierotofy** [comment]
Hey @superset1 :wave: can you elaborate how this is failing? Can you post reproduction steps?
