### ISSUE TITLE
ERROR:stanza:Cannot load model - Serbian Language resulting in LibreTranslate crash 

### ISSUE THREAD

**Issue by learning4life** [LibreTranslate/LibreTranslate#536]
After building the libretranslate docker image with models included, the following ERROR is reported when libretranslate is used in an offline OR online environment:

```
ERROR: Cannot load model from /home/libretranslate/.local/share/argos-translate/packages/translate-sr_en-1_9/stanza/sr/tokenize/set.pt
libra-1 | ERROR:stanza:Cannot load model from /home/libretranslate/.local/share/argos-translate/packages/translate-sr_en-1_9/stanza/sr/tokenize/set.pt
libra-1 | ERROR:libretranslate.app:Exception on /translate [POST] 
```

Code used:
```bash
git clone https://github.com/LibreTranslate/LibreTranslate --branch v1.5.1
```
```bash
docker build --build-arg with_models=true -f docker/Dockerfile -t libretranslate:v1.5.1 .
```

```bash
curl -X POST http://localhost:5000/trans
late -H 'Content-Type: application/json' -d '{"q": ["на свак дичан славан рад~"
,"Сложи српску браћу драгу"],"source": "sr","target": "en","format": "text"}'
```

**Comment by PJ-Finlay** [comment]
I reproduced this bug:
```
Traceback (most recent call last):
  File "/home/pj/Downloads/env/lib/python3.10/site-packages/argostranslategui/gui.py", line 39, in run
    translated_text = self.translation_function()
  File "/home/pj/Downloads/env/lib/python3.10/site-packages/argostranslate/translate.py", line 63, in translate
    return self.hypotheses(input_text, num_hypotheses=1)[0].value
  File "/home/pj/Downloads/env/lib/python3.10/site-packages/argostranslate/translate.py", line 238, in hypotheses
    t1_hypotheses = self.t1.hypotheses(input_text, num_hypotheses)
  File "/home/pj/Downloads/env/lib/python3.10/site-packages/argostranslate/translate.py", line 296, in hypotheses
    translated_paragraph = self.underlying.hypotheses(
  File "/home/pj/Downloads/env/lib/python3.10/site-packages/argostranslate/translate.py", line 173, in hypotheses
    apply_packaged_translation(
  File "/home/pj/Downloads/env/lib/python3.10/site-packages/argostranslate/translate.py", line 418, in apply_packaged_translation
    stanza_pipeline = stanza.Pipeline(
  File "/home/pj/Downloads/env/lib/python3.10/site-packages/stanza/pipeline/core.py", line 111, in __init__
    self.processors[processor_name] = NAME_TO_PROCESSOR_CLASS[processor_name](config=curr_processor_config,
  File "/home/pj/Downloads/env/lib/python3.10/site-packages/stanza/pipeline/processor.py", line 146, in __init__
    self._set_up_model(config, use_gpu)
  File "/home/pj/Downloads/env/lib/python3.10/site-packages/stanza/pipeline/tokenize_processor.py", line 38, in _set_up_model
    self._trainer = Trainer(model_file=config['model_path'], use_cuda=use_gpu)
  File "/home/pj/Downloads/env/lib/python3.10/site-packages/stanza/models/tokenize/trainer.py", line 19, in __init__
    self.load(model_file)
  File "/home/pj/Downloads/env/lib/python3.10/site-packages/stanza/models/tokenize/trainer.py", line 85, in load
    checkpoint = torch.load(filename, lambda storage, loc: storage)
  File "/home/pj/Downloads/env/lib/python3.10/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/pj/Downloads/env/lib/python3.10/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/pj/Downloads/env/lib/python3.10/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/pj/.local/share/argos-translate/packages/translate-sr_en-1_9/stanza/sr/tokenize/set.pt'
Aborted (core dumped)
```

**Comment by PJ-Finlay** [comment]
I removed the Serbian model from the package index:
https://github.com/argosopentech/argospm-index/commit/527a93220920bc7b53d6108b53f280544cf740dc
