### ISSUE TITLE
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### ISSUE THREAD

**Issue by osmansonsuz** [LibreTranslate/LibreTranslate#539]
My web app is not working.Only english to english is working.Other than that every language is responding this error.I have tried reinstalling everything,reinstalling models and all the stuff.I am using uwsgi btw.

```
[2023-11-15 16:38:37,775] ERROR in app: Exception on /translate [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/dist-packages/libretranslate/app.py", line 283, in func
    return f(*a, **kw)
  File "/usr/local/lib/python3.10/dist-packages/libretranslate/app.py", line 629, in translate
    raise e
  File "/usr/local/lib/python3.10/dist-packages/libretranslate/app.py", line 613, in translate
    translated_text = improve_translation_formatting(q, translator.translate(q))
  File "/usr/local/lib/python3.10/dist-packages/argostranslate/translate.py", line 63, in translate
    return self.hypotheses(input_text, num_hypotheses=1)[0].value
  File "/usr/local/lib/python3.10/dist-packages/argostranslate/translate.py", line 296, in hypotheses
    translated_paragraph = self.underlying.hypotheses(
  File "/usr/local/lib/python3.10/dist-packages/argostranslate/translate.py", line 173, in hypotheses
    apply_packaged_translation(
  File "/usr/local/lib/python3.10/dist-packages/argostranslate/translate.py", line 425, in apply_packaged_translation
    stanza_sbd = stanza_pipeline(input_text)
  File "/usr/local/lib/python3.10/dist-packages/stanza/pipeline/core.py", line 166, in __call__
    doc = self.process(doc)
  File "/usr/local/lib/python3.10/dist-packages/stanza/pipeline/core.py", line 160, in process
    doc = self.processors[processor_name].process(doc)
  File "/usr/local/lib/python3.10/dist-packages/stanza/pipeline/tokenize_processor.py", line 85, in process
    _, _, _, document = output_predictions(None, self.trainer, batches, self.vocab, None,
  File "/usr/local/lib/python3.10/dist-packages/stanza/models/tokenize/utils.py", line 90, in output_predictions
    pred = np.argmax(trainer.predict(batch), axis=2)
  File "/usr/local/lib/python3.10/dist-packages/stanza/models/tokenize/trainer.py", line 67, in predict
    pred = self.model(units, features)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/stanza/models/tokenize/model.py", line 65, in forward
    tok0 = self.tok_clf(inp)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: could not create a primitive descriptor for a matmul primitive
[pid: 9677|app: 0|req: 6/27] 159.146.95.35 () {60 vars in 1328 bytes} [Wed Nov 15 16:38:37 2023] POST /translate => generated 167 bytes in 427 msecs (HTTP/2.0 500) 9 headers in 457 bytes (1 switches on core 0)
```

**Comment by osmansonsuz** [comment]
> How did you install LibreTranslate? Can you check your version of pytorch? I know there's been issues with their latest releases.
> 
> `pytorch==2.0.1`

I installed like this. pip install libretranslate
And then cloned the repository.
My pytorch version is 2.1.0. So it's a problem related to the pytorch 2.0.1 ?

**Comment by pierotofy** [comment]
Likely; can you try to downgrade pytorch:

`pip install -U pytorch==2.0.1`

And see if it works?

**Comment by osmansonsuz** [comment]
> Likely; can you try to downgrade pytorch:
> 
> `pip install -U pytorch==2.0.1`
> 
> And see if it works?

Wow... just wow... thank you so much.
I tried this and got this error.
`The package named for PyTorch is "torch"`
Then i tried this `pip install -U torch==2.0.1` and it started working... Thank you so much.
