### ISSUE TITLE
Numpy is not available

### ISSUE THREAD

**Issue by JasminDreasond** [LibreTranslate/LibreTranslate#638]
Command used: `docker compose up -d --build`
Ubuntu 24.04

This is happening in the docker version now in the version 1.6.0:

    ERROR:libretranslate.app:Exception on /translate [POST]
    Traceback (most recent call last):
      File "/app/venv/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
        response = self.full_dispatch_request()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/app/venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
        rv = self.handle_user_exception(e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/app/venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
        rv = self.dispatch_request()
             ^^^^^^^^^^^^^^^^^^^^^^^
      File "/app/venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
        return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/app/venv/lib/python3.11/site-packages/libretranslate/app.py", line 349, in time_func
        return func(*a, **kw)
               ^^^^^^^^^^^^^^
      File "/app/venv/lib/python3.11/site-packages/libretranslate/app.py", line 323, in func
        return f(*a, **kw)
               ^^^^^^^^^^^
      File "/app/venv/lib/python3.11/site-packages/libretranslate/app.py", line 699, in translate
        raise e
      File "/app/venv/lib/python3.11/site-packages/libretranslate/app.py", line 686, in translate
        hypotheses = translator.hypotheses(q, num_alternatives + 1)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/app/venv/lib/python3.11/site-packages/argostranslate/translate.py", line 296, in hypotheses
        translated_paragraph = self.underlying.hypotheses(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/app/venv/lib/python3.11/site-packages/argostranslate/translate.py", line 173, in hypotheses
        apply_packaged_translation(
      File "/app/venv/lib/python3.11/site-packages/argostranslate/translate.py", line 425, in apply_packaged_translation
        stanza_sbd = stanza_pipeline(input_text)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/app/venv/lib/python3.11/site-packages/stanza/pipeline/core.py", line 166, in __call__
        doc = self.process(doc)
              ^^^^^^^^^^^^^^^^^
      File "/app/venv/lib/python3.11/site-packages/stanza/pipeline/core.py", line 160, in process
        doc = self.processors[processor_name].process(doc)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/app/venv/lib/python3.11/site-packages/stanza/pipeline/tokenize_processor.py", line 85, in process
        _, _, _, document = output_predictions(None, self.trainer, batches, self.vocab, None,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/app/venv/lib/python3.11/site-packages/stanza/models/tokenize/utils.py", line 85, in output_predictions
        batch = data_generator.next(eval_offsets=offsets)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/app/venv/lib/python3.11/site-packages/stanza/models/tokenize/data.py", line 206, in next
        units, labels, features = list(map(convert, [(units, np.int64), (labels, np.int64), (features, np.float32)]))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/app/venv/lib/python3.11/site-packages/stanza/models/tokenize/data.py", line 204, in <lambda>
        convert = lambda t: (torch.from_numpy(np.array(t[0], dtype=t[1])))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    RuntimeError: Numpy is not available

**Comment by tcitworld** [comment]
We have the same issue when installing from pip.

**Comment by ldidry** [comment]
The problem is with numpy >=2. `pip install numpy==1.26.4` makes it work.

**Comment by AriesJ12** [comment]
if you are using docker you may include the numpy pip install command in the docker/Docker file of the libretranslate; the error stopped appear, atleast for me
![image](https://github.com/LibreTranslate/LibreTranslate/assets/119474970/041c21a4-0992-4adb-8508-72a27934d9b2)

**Comment by silentoplayz** [comment]
> if you are using docker you may include the numpy pip install command in the docker/Docker file of the libretranslate; the error stopped to appear, atleast for me ![image](https://private-user-images.githubusercontent.com/119474970/343617413-041c21a4-0992-4adb-8508-72a27934d9b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNDUyODYsIm5iZiI6MTcyMDE0NDk4NiwicGF0aCI6Ii8xMTk0NzQ5NzAvMzQzNjE3NDEzLTA0MWMyMWE0LTA5OTItNGFkYi04NTA4LTcyYTI3OTM0ZDliMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQwMjAzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjkyNmFjNWI0MDE1ZGYzM2M3NzY2OGE2MzZhMmRjN2U4OGNjNDY5MGUxOWYyY2JkNThiNzllYmQyMDIxNGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XCCxtwEqf9hyz35sga0Udfm0uF6PK-OCcDH13xvcJYU)

Can this be submitted as a PR for the Dockerfile?
>   && ./venv/bin/pip install "numpy<2" \

**Comment by bogdan-nikitin** [comment]
This is still a problem when installing via pip
