### ISSUE TITLE
A module that was compiled using NumPy 1.x cannot be run in NumPy 2.0.0 as it may crash.

### ISSUE THREAD

**Issue by Fi1osof** [LibreTranslate/LibreTranslate#642]
I try to run 
```sh
docker compose up -d --build
```

After start on translate got error
```
docker logs -f libretranslate
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 2

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/local/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/venv/lib/python3.11/site-packages/waitress/task.py", line 84, in handler_thread
    task.service()
  File "/app/venv/lib/python3.11/site-packages/waitress/channel.py", line 428, in service
    task.service()
  File "/app/venv/lib/python3.11/site-packages/waitress/task.py", line 168, in service
    self.execute()
  File "/app/venv/lib/python3.11/site-packages/waitress/task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/app/venv/lib/python3.11/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "/app/venv/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/venv/lib/python3.11/site-packages/libretranslate/app.py", line 349, in time_func
    return func(*a, **kw)
  File "/app/venv/lib/python3.11/site-packages/libretranslate/app.py", line 323, in func
    return f(*a, **kw)
  File "/app/venv/lib/python3.11/site-packages/libretranslate/app.py", line 686, in translate
    hypotheses = translator.hypotheses(q, num_alternatives + 1)
  File "/app/venv/lib/python3.11/site-packages/argostranslate/translate.py", line 296, in hypotheses
    translated_paragraph = self.underlying.hypotheses(
  File "/app/venv/lib/python3.11/site-packages/argostranslate/translate.py", line 173, in hypotheses
    apply_packaged_translation(
  File "/app/venv/lib/python3.11/site-packages/argostranslate/translate.py", line 418, in apply_packaged_translation
    stanza_pipeline = stanza.Pipeline(
  File "/app/venv/lib/python3.11/site-packages/stanza/pipeline/core.py", line 111, in __init__
    self.processors[processor_name] = NAME_TO_PROCESSOR_CLASS[processor_name](config=curr_processor_config,
  File "/app/venv/lib/python3.11/site-packages/stanza/pipeline/processor.py", line 146, in __init__
    self._set_up_model(config, use_gpu)
  File "/app/venv/lib/python3.11/site-packages/stanza/pipeline/tokenize_processor.py", line 38, in _set_up_model
    self._trainer = Trainer(model_file=config['model_path'], use_cuda=use_gpu)
  File "/app/venv/lib/python3.11/site-packages/stanza/models/tokenize/trainer.py", line 19, in __init__
    self.load(model_file)
  File "/app/venv/lib/python3.11/site-packages/stanza/models/tokenize/trainer.py", line 85, in load
    checkpoint = torch.load(filename, lambda storage, loc: storage)
  File "/app/venv/lib/python3.11/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/app/venv/lib/python3.11/site-packages/torch/serialization.py", line 1043, in _legacy_load
    result = unpickler.load()
  File "/app/venv/lib/python3.11/site-packages/torch/serialization.py", line 975, in persistent_load
    obj = cast(Storage, torch.UntypedStorage(nbytes))
/app/venv/lib/python3.11/site-packages/torch/serialization.py:975: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  obj = cast(Storage, torch.UntypedStorage(nbytes))
ERROR:libretranslate.app:Exception on /translate [POST]
Traceback (most recent call last):
  File "/app/venv/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/libretranslate/app.py", line 349, in time_func
    return func(*a, **kw)
           ^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/libretranslate/app.py", line 323, in func
    return f(*a, **kw)
           ^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/libretranslate/app.py", line 699, in translate
    raise e
  File "/app/venv/lib/python3.11/site-packages/libretranslate/app.py", line 686, in translate
    hypotheses = translator.hypotheses(q, num_alternatives + 1)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/argostranslate/translate.py", line 296, in hypotheses
    translated_paragraph = self.underlying.hypotheses(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/argostranslate/translate.py", line 173, in hypotheses
    apply_packaged_translation(
  File "/app/venv/lib/python3.11/site-packages/argostranslate/translate.py", line 425, in apply_packaged_translation
    stanza_sbd = stanza_pipeline(input_text)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/stanza/pipeline/core.py", line 166, in __call__
    doc = self.process(doc)
          ^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/stanza/pipeline/core.py", line 160, in process
    doc = self.processors[processor_name].process(doc)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/stanza/pipeline/tokenize_processor.py", line 85, in process
    _, _, _, document = output_predictions(None, self.trainer, batches, self.vocab, None,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/stanza/models/tokenize/utils.py", line 85, in output_predictions
    batch = data_generator.next(eval_offsets=offsets)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/stanza/models/tokenize/data.py", line 206, in next
    units, labels, features = list(map(convert, [(units, np.int64), (labels, np.int64), (features, np.float32)]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/stanza/models/tokenize/data.py", line 204, in <lambda>
    convert = lambda t: (torch.from_numpy(np.array(t[0], dtype=t[1])))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Numpy is not available

```

UPD: this works fine: 
```sh
docker run -ti --rm -p 127.0.0.1:5000:5000 libretranslate/libretranslate
```

**Comment by PJ-Finlay** [comment]
https://github.com/LibreTranslate/LibreTranslate/issues/638

**Comment by Fi1osof** [comment]
Duplicate: https://github.com/LibreTranslate/LibreTranslate/issues/638
