### ISSUE TITLE
libcusolver.so.11: failed to map segment from shared object

### ISSUE THREAD

**Issue by a2rette** [LibreTranslate/LibreTranslate#655]
Hi,

I am trying to have libretranslate running on a o2switch virtual server.
pip install libretranslate ran smoothly.
When i execute libretranslate, it end up with **libcusolver.so.11: failed to map segment from shared object**

i added some print that tells me that _preload_cuda_deps() is successfull when loading the 7 first libs of the array, but ctypes.CDLL fails on the 8th, libcusolver.so.11, which is here with correct permissions.

What could it be  ? Insufficient memory ?

stderr is here :
```
Traceback (most recent call last):
  File "/pathToProject/lib64/python3.8/site-packages/torch/__init__.py", line 170, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/opt/alt/python38/lib64/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcurand.so.10: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pathToProject/bin/libretranslate", line 5, in <module>
    from libretranslate.main import main
  File "/pathToProject/lib/python3.8/site-packages/libretranslate/__init__.py", line 2, in <module>
    from .main import main
  File "/pathToProject/lib/python3.8/site-packages/libretranslate/main.py", line 5, in <module>
    from libretranslate.app import create_app
  File "/pathToProject/lib/python3.8/site-packages/libretranslate/app.py", line 12, in <module>
    import argostranslatefiles
  File "/pathToProject/lib/python3.8/site-packages/argostranslatefiles/__init__.py", line 1, in <module>
    from argostranslatefiles.argostranslatefiles import *
  File "/pathToProject/lib/python3.8/site-packages/argostranslatefiles/argostranslatefiles.py", line 1, in <module>
    from argostranslate.translate import ITranslation
  File "/pathToProject/lib/python3.8/site-packages/argostranslate/translate.py", line 5, in <module>
    import ctranslate2
  File "/pathToProject/lib64/python3.8/site-packages/ctranslate2/__init__.py", line 55, in <module>
    from ctranslate2 import converters, models, specs
  File "/pathToProject/lib64/python3.8/site-packages/ctranslate2/converters/__init__.py", line 1, in <module>
    from ctranslate2.converters.converter import Converter
  File "/pathToProject/lib64/python3.8/site-packages/ctranslate2/converters/converter.py", line 8, in <module>
    from ctranslate2.specs.model_spec import ACCEPTED_MODEL_TYPES, ModelSpec
  File "/pathToProject/lib64/python3.8/site-packages/ctranslate2/specs/__init__.py", line 1, in <module>
    from ctranslate2.specs.attention_spec import RotaryScalingType
  File "/pathToProject/lib64/python3.8/site-packages/ctranslate2/specs/attention_spec.py", line 5, in <module>
    from ctranslate2.specs import common_spec, model_spec
  File "/pathToProject/lib64/python3.8/site-packages/ctranslate2/specs/common_spec.py", line 3, in <module>
    from ctranslate2.specs import model_spec
  File "/pathToProject/lib64/python3.8/site-packages/ctranslate2/specs/model_spec.py", line 18, in <module>
    import torch
  File "/pathToProject/lib64/python3.8/site-packages/torch/__init__.py", line 230, in <module>
    _load_global_deps()
  File "/pathToProject/lib64/python3.8/site-packages/torch/__init__.py", line 191, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/pathToProject/lib64/python3.8/site-packages/torch/__init__.py", line 155, in _preload_cuda_deps
    ctypes.CDLL(lib_path)
  File "/opt/alt/python38/lib64/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /pathToProject/lib/python3.8/site-packages/nvidia/cusolver/lib/libcusolver.so.11: failed to map segment from shared object
```

**Comment by a2rette** [comment]
Hi dingedi,
Sorry I should give up.
Thank you for taking the time to look at this problem.
