### ISSUE TITLE
bug: struct.error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by silentoplayz** [LibreTranslate/LibreTranslate#667]
LibreTranslate is spamming this error in Docker Desktop logs until I stop the container from running:

```
2024-08-25 02:15:06 WARNING:root:Exception raised while handling cache file 'db/sessions/a14d1d697f4d3c6496f2d5b2a4f6e712'
2024-08-25 02:15:06 Traceback (most recent call last):
2024-08-25 02:15:06   File "/app/venv/lib/python3.11/site-packages/cachelib/file.py", line 137, in _remove_expired
2024-08-25 02:15:06     expires = struct.unpack("I", f.read(4))[0]
2024-08-25 02:15:06               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-25 02:15:06 struct.error: unpack requires a buffer of 4 bytes
2024-08-25 02:15:06 WARNING:root:Exception raised while handling cache file 'db/sessions/a14d1d697f4d3c6496f2d5b2a4f6e712'
2024-08-25 02:15:06 Traceback (most recent call last):
2024-08-25 02:15:06   File "/app/venv/lib/python3.11/site-packages/cachelib/file.py", line 155, in _remove_older
2024-08-25 02:15:06     timestamp = struct.unpack("I", f.read(4))[0]
2024-08-25 02:15:06                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-25 02:15:06 struct.error: unpack requires a buffer of 4 bytes
```

I am using `libretranslate/libretranslate:v1.6.0`  - sha256:275ecc12a296a7f28148882c412298a212e1ccffd5595759d30bac5300ea5dbb

**Comment by pierotofy** [comment]
Should be fixed with #890. Thanks for the report!
