### ISSUE TITLE
Permission error, same as #378 which is now closed, but I cannot re-open

### ISSUE THREAD

**Issue by janaxhell** [LibreTranslate/LibreTranslate#669]
I posted this as a follow-up to #378 , but it was closed already and passed unnoticed. Since I cannot re-open that, I am opening a new one. This hasn't changed since last april.

Just tried to deploy on Docker and got exactly the same error. I've tried to tinker adding PUID/PGID variables, but the error won't go away. Restarted several times and it did not make any difference.
My compose:

```
version: '3.8'
services:
    libretranslate:
      container_name: libretranslate
      image: libretranslate/libretranslate
      tty: true
      stdin_open: true
      ports:
        - 5000:5000
## Uncomment this section and the libretranslate_api_keys volume if you want to backup your API keys

      environment:
        - LT_API_KEYS=true
        - LT_API_KEYS_DB_PATH=/app/db/api_keys.db # Same result as `db/api_keys.db` or `./db/api_keys.db`
        - PUID=998
        - PGID=100
        
## Uncomment these vars and libretranslate_models volume to optimize loading time.

        - LT_UPDATE_MODELS=true
        - LT_LOAD_ONLY=it,jp,en
      volumes:
        - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/libretranslate/data:/home/libretranslate/.local/share
        - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/libretranslate/cache:/home/libretranslate/.local/cache
        - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/libretranslate/libretranslate_api_keys:/app/db
        
# Keep the models in a docker volume, to avoid re-downloading on startup

        - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/libretranslate/libretranslate_models:/home/libretranslate/.local:rw
  
networks:
  default:
    external:
      name: omv2

```

The error log:

```
PermissionError: [Errno 13] Permission denied: '/home/libretranslate/.local/share/argos-translate'
Traceback (most recent call last):
  File "/app/./venv/bin/libretranslate", line 5, in <module>
    from libretranslate.main import main
  File "/app/venv/lib/python3.11/site-packages/libretranslate/__init__.py", line 2, in <module>
    from .main import main
  File "/app/venv/lib/python3.11/site-packages/libretranslate/main.py", line 5, in <module>
    from libretranslate.app import create_app
  File "/app/venv/lib/python3.11/site-packages/libretranslate/app.py", line 12, in <module>
    import argostranslatefiles
  File "/app/venv/lib/python3.11/site-packages/argostranslatefiles/__init__.py", line 1, in <module>
    from argostranslatefiles.argostranslatefiles import *
  File "/app/venv/lib/python3.11/site-packages/argostranslatefiles/argostranslatefiles.py", line 1, in <module>
    from argostranslate.translate import ITranslation
  File "/app/venv/lib/python3.11/site-packages/argostranslate/translate.py", line 10, in <module>
    from argostranslate import apis, fewshot, package, sbd, settings
  File "/app/venv/lib/python3.11/site-packages/argostranslate/package.py", line 13, in <module>
    from argostranslate import networking, settings
  File "/app/venv/lib/python3.11/site-packages/argostranslate/networking.py", line 6, in <module>
    from argostranslate.utils import error, info
  File "/app/venv/lib/python3.11/site-packages/argostranslate/utils.py", line 4, in <module>
    from argostranslate import settings
  File "/app/venv/lib/python3.11/site-packages/argostranslate/settings.py", line 19, in <module>
    os.makedirs(data_dir, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/home/libretranslate/.local/share/argos-translate'
```

**Comment by Morethanevil** [comment]
Had the same problem, the UID of libretranslate is 1032. I used `chown -R 1032:1032` on my volumes, then started the container again. Worked without problems :)

**Comment by janaxhell** [comment]
Ahh, thank you! It works now!
