### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by SvenVincent** [LibreTranslate/LibreTranslate#675]
(URLError(ConnectionRefusedError(111, 'Connection refused')),)
(RecursionError('maximum recursion depth exceeded while calling a Python object'),)
(RecursionError('maximum recursion depth exceeded while calling a Python object'),)
(RecursionError('maximum recursion depth exceeded'),)
(RecursionError('maximum recursion depth exceeded while getting the str of an object'),)
(RecursionError('maximum recursion depth exceeded while calling a Python object'),)
(RecursionError('maximum recursion depth exceeded'),)
(RecursionError('maximum recursion depth exceeded while calling a Python object'),)
(RecursionError('maximum recursion depth exceeded while calling a Python object'),)
Updating language models
Traceback (most recent call last):
  File "/app/./venv/bin/libretranslate", line 8, in <module>
Cannot update models (normal if you're offline): maximum recursion depth exceeded while calling a Python object
    sys.exit(main())
             ^^^^^^
  File "/app/venv/lib/python3.11/site-packages/libretranslate/main.py", line 226, in main
    app = create_app(args)
          ^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/libretranslate/app.py", line 191, in create_app
    language_target_fallback = languages[1] if len(languages) >= 2 else languages[0]
                                                                        ~~~~~~~~~^^^
IndexError: list index out of range

**Comment by mgl-pub** [comment]
same error

**Comment by bi305** [comment]
any  help on this

**Comment by satonotdead** [comment]
It's a general error, you need to check logs and/or config files.

**Comment by pierotofy** [comment]
For anyone that encounters this issue, *please* provide reproduction steps (how did you trigger this error? details on your environment? how did you run LibreTranslate?)

**Comment by satonotdead** [comment]
In my case it was related to bad configuration from my side, fixing them stopped this error as well.

**Comment by pierotofy** [comment]
Closing, if there are reproduction steps we can look further into it, although this looks like it's due to misconfiguration/network issues.
