### ISSUE TITLE
Library cublas64_12.dll is not found or cannot be loaded

### ISSUE THREAD

**Issue by dokurorz** [LibreTranslate/LibreTranslate#694]
Env:
- Windows 10 22H2
- Python 3.10.6
- libretranslate 1.6.1

When GPU hardware acceleration is enabled, the following error is thrown:
```
Traceback (most recent call last):
  File "C:\Users\Dokuro\Documents\LibreTranslate\.venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Dokuro\Documents\LibreTranslate\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Dokuro\Documents\LibreTranslate\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Dokuro\Documents\LibreTranslate\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Dokuro\Documents\LibreTranslate\.venv\lib\site-packages\libretranslate\app.py", line 350, in time_func
    return func(*a, **kw)
  File "C:\Users\Dokuro\Documents\LibreTranslate\.venv\lib\site-packages\libretranslate\app.py", line 324, in func
    return f(*a, **kw)
  File "C:\Users\Dokuro\Documents\LibreTranslate\.venv\lib\site-packages\libretranslate\app.py", line 700, in translate
    raise e
  File "C:\Users\Dokuro\Documents\LibreTranslate\.venv\lib\site-packages\libretranslate\app.py", line 687, in translate
    hypotheses = translator.hypotheses(q, num_alternatives + 1)
  File "C:\Users\Dokuro\Documents\LibreTranslate\.venv\lib\site-packages\argostranslate\translate.py", line 238, in hypotheses
    t1_hypotheses = self.t1.hypotheses(input_text, num_hypotheses)
  File "C:\Users\Dokuro\Documents\LibreTranslate\.venv\lib\site-packages\argostranslate\translate.py", line 296, in hypotheses
    translated_paragraph = self.underlying.hypotheses(
  File "C:\Users\Dokuro\Documents\LibreTranslate\.venv\lib\site-packages\argostranslate\translate.py", line 173, in hypotheses
    apply_packaged_translation(
  File "C:\Users\Dokuro\Documents\LibreTranslate\.venv\lib\site-packages\argostranslate\translate.py", line 464, in apply_packaged_translation
    translated_batches = translator.translate_batch(
RuntimeError: Library cublas64_12.dll is not found or cannot be loaded
```

I noticed that the dependency requirement for `argostranslate` is `ctranslate2 >=4.0,<5`, but versions of `ctranslate2` after 4.0 only support cuda 12.x. The latest version of LibreTranslate still requires `torch ==2.0.1`, which only supports up to cuda 11.8, and for cuda versions below 12.x, only `cublas64_11 .dll` is available.

This error seems to occur only on Windows systems, so I looked up the issue [OpenNMT/CTranslate2 issues#1630](https://github.com/OpenNMT/CTranslate2/issues/1630#issuecomment-1967641755).

So my temporary solution is to copy the cublas64_11.dll file from the .venv\Lib\site-packages\torch\lib\ directory and rename it as cublas64_12.dll.

**Comment by pierotofy** [comment]
Should be fixed with the latest version 🙏
