### ISSUE TITLE
gunicorn: RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by Enteee** [LibreTranslate/LibreTranslate#716]
After running `libretranslate-v1.6.2-cuda` for a while inside a kubernetes cluster I do get the exception below for each new connection. 

```
Error submitting job "remove_translated_files (trigger: interval[0:30:00], next run at: 2024-12-17 19:05:07 UTC)" to executor "default"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/apscheduler/schedulers/base.py", line 978, in _process_jobs
    executor.submit_job(job, run_times)
  File "/usr/local/lib/python3.8/dist-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/usr/local/lib/python3.8/dist-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 188, in submit
    self._adjust_thread_count()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 213, in _adjust_thread_count
    t.start()
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

I am running libretranslate inside the gunicorn. Below the relevant section from my Dockerfile:

```Dockerfile
ARG LIBRETRANSLATE_IMAGE_VERSION="v1.6.2"
FROM libretranslate/libretranslate:${LIBRETRANSLATE_IMAGE_VERSION}-cuda

# Package versions
ARG GUNICORN_VERSION=22.0.0

RUN set -exu \
    && pip install --no-cache-dir -I "gunicorn[gevent]==${GUNICORN_VERSION}"

EXPOSE 5000

# We overwrite here ARGOS_DEVICE_TYPE which is set in the
# base image to `cuda`. This will allow running this image
# on machines without cuda installed
#
# Can be removed if the following is implemented:
# - https://github.com/LibreTranslate/LibreTranslate/issues/713
#
# Reference:
# - https://github.com/argosopentech/argos-translate/blob/master/README.md#gpu-acceleration
# - https://github.com/LibreTranslate/LibreTranslate/blob/6796e95acd2969cd1c727673a0eca7f7856e8092/docker/cuda.Dockerfile#L3C5-L3C22
ENV ARGOS_DEVICE_TYPE=auto

ENTRYPOINT ["gunicorn", "wsgi:app", "--bind", "0.0.0.0:5000", "--access-logfile", "-", "--timeout", "180"]

```

Checking with my process manager, i can confirm that gunicorn has allocated 69 000 threads.

**Comment by pierotofy** [comment]
You probably need to set a `--max-requests` option for gunicorn. https://docs.gunicorn.org/en/stable/settings.html#max-requests

This isn't an issue of LibreTranslate per-se (potential memory leaks aside). So I'll close this for now. For further discussion, let's move the conversation over to https://community.libretranslate.com ? 🙏

**Comment by Enteee** [comment]
Suggesting `--max-requests` as a solution for this does not seem to be a good way forward with this issues as `--max-requests` is merely just a workaround for bad thread handling. As even the documentation of `--max-requests` state:
> [...] This is a simple method to help limit the damage of memory leaks. [...]

So I'd definitely keep this open as there is a memory leak / threading issue somewhere in libretranslate.

**Comment by pierotofy** [comment]
Yes, perfectly correct. We're aware of the leak and are tracking it in #545 as well as https://github.com/argosopentech/argos-translate/issues/337

**Comment by RobinPijnappelsAvans** [comment]
When will this issue be fixed @pierotofy?

**Comment by 736-c41-2c1-e464fc974** [comment]
I also see this after a while even with `--max-requests` set. What makes this even worse is that the libretranslate responds with a 500 and health check `scripts/healthcheck.py` does not `raise_for_status()`. That's why I opened #822 . 

@pierotofy  can you please re-open this issue?
